/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectui;

import db.DBconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author charm
 */
public class Booking extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistrationData
     */
    Connection conn = null;
    PreparedStatement pst = null;
    public int val=0;
    
    public Booking() {
        initComponents();
      
    }

    public String id="";
    public Booking(String id2) {
        initComponents();
       employeeId_txt.setText(id2);
       try{
       Connection conn = DBconnect.connect();
       //JOptionPane.showMessageDialog(null, "Error", "Database Error", JOptionPane.ERROR_MESSAGE);
      // String c = "SELECT * FROM `booking` order by booking_Id desc limit 1";
      String c = "SELECT max(booking_Id) as max_inv from booking";
       Statement st = null; 
       st = conn.createStatement();
       ResultSet rs = st.executeQuery(c);
    
       while(rs.next())
       {
            val = rs.getInt("max_inv");
       }    
       val = val + 1;
       booking_id.setText(String.valueOf(val));
       }
       catch(SQLException e1) { JOptionPane.showMessageDialog(null, "Error", "Database Error", JOptionPane.ERROR_MESSAGE);}
       catch(Exception e) { JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE);}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt = new javax.swing.JTable();
        search_btn = new javax.swing.JButton();
        bookingType_cmb1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        insertregdata_txt = new javax.swing.JButton();
        employeeId_txt = new javax.swing.JTextField();
        checkOutDate_txt = new javax.swing.JTextField();
        bookingType_cmb = new javax.swing.JComboBox<>();
        roomNo_txt = new javax.swing.JTextField();
        customer = new javax.swing.JTextField();
        booking_id = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setMaximizable(true);
        setResizable(true);

        jPanel1.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.setAutoscrolls(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter Booking Details");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        jt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(jt);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 680, 450));

        search_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        search_btn.setText("Search");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });
        jPanel2.add(search_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 200, 101, 32));

        bookingType_cmb1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bookingType_cmb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Room type", "Master Suite", "Mini-Suite", "Junior Suite" }));
        bookingType_cmb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingType_cmb1ActionPerformed(evt);
            }
        });
        jPanel2.add(bookingType_cmb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 215, 32));

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 560, 101, 44));

        insertregdata_txt.setBackground(new java.awt.Color(0, 153, 153));
        insertregdata_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        insertregdata_txt.setText("Insert");
        insertregdata_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertregdata_txtActionPerformed(evt);
            }
        });
        jPanel2.add(insertregdata_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 101, 44));

        employeeId_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        employeeId_txt.setEnabled(false);
        jPanel2.add(employeeId_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 140, 150, -1));

        checkOutDate_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(checkOutDate_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 390, 324, -1));

        bookingType_cmb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bookingType_cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select booking type", "Full Board", "Half Board" }));
        jPanel2.add(bookingType_cmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 333, 215, -1));

        roomNo_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(roomNo_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 268, 324, -1));

        customer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 208, 324, -1));

        booking_id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        booking_id.setText("Booking ID");
        jPanel2.add(booking_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Customer NIC");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 214, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Room Number");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 274, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Booking Type");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 336, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("No. of days");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 396, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Employee ID");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Booking ID");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 143, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        // TODO add your handling code here:
        try
        {
            Connection conn = DBconnect.connect();
            String sql = "SELECT * FROM room where availability =1 and room_Type='"+bookingType_cmb1.getSelectedItem()+"'";
            pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            jt.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch (Exception e)
        {

        }
    }//GEN-LAST:event_search_btnActionPerformed

    private void bookingType_cmb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingType_cmb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingType_cmb1ActionPerformed

    private void insertregdata_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertregdata_txtActionPerformed
        if(customer.getText().equals("")){JOptionPane.showMessageDialog(null, "Error", "NIC should not be empty", JOptionPane.ERROR_MESSAGE);}
        else if(roomNo_txt.getText().equals("")) {JOptionPane.showMessageDialog(null, "Error", "Room number should not be empty", JOptionPane.ERROR_MESSAGE);}
        else if(bookingType_cmb.getSelectedIndex()==0) {JOptionPane.showMessageDialog(null, "Error", "Select room booikng type", JOptionPane.ERROR_MESSAGE);}
        else if(checkOutDate_txt.getText().equals("")) {JOptionPane.showMessageDialog(null, "Error", "Select number of days", JOptionPane.ERROR_MESSAGE);}
        else{
        int x = JOptionPane.showConfirmDialog(null, "Do you want to save data?");

        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
        LocalDate today = LocalDate.now();

        if(x==0)
        {
            //String booking_Id = bookId_txt.getText();
            String rNo = roomNo_txt.getText();
            String bCategory = bookingType_cmb.getSelectedItem().toString();
            //String cidate = checkInDate_txt.getText();
            /*try {
                Date date1=new SimpleDateFormat("yyyy-mm-dd").parse(cidate);
            } catch (ParseException ex) {
                Logger.getLogger(Booking.class.getName()).log(Level.SEVERE, null, ex);
            }*/
            int codate = Integer.parseInt(checkOutDate_txt.getText());
            int id2 = Integer.parseInt(id);
            /*try {
                Date date1=new SimpleDateFormat("yyyy-mm-dd").parse(codate);
            } catch (ParseException ex) {
                Logger.getLogger(Booking.class.getName()).log(Level.SEVERE, null, ex);
            }*/
            String empId = employeeId_txt.getText();

            try {
                String q = "INSERT into booking values('"+booking_id.getText()+"','"+rNo+"','"+today+"','"+codate+"','"+bookingType_cmb.getSelectedItem()+"','"+employeeId_txt.getText()+"','"+customer.getText()+"')";
                pst = conn.prepareStatement(q);
                pst.executeQuery(q);
                String r = "UPDATE room SET availability='0' where room_No='"+rNo+"'";
                pst = conn.prepareStatement(r);
                pst.executeQuery(r);
            }
            catch (SQLException e)
            {
                
                JOptionPane.showMessageDialog(null, "Error", "Database Error", JOptionPane.INFORMATION_MESSAGE);
            }}
        }
    }//GEN-LAST:event_insertregdata_txtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Booking b  = new Booking();
                b.setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bookingType_cmb;
    private javax.swing.JComboBox<String> bookingType_cmb1;
    private javax.swing.JLabel booking_id;
    private javax.swing.JTextField checkOutDate_txt;
    private javax.swing.JTextField customer;
    private javax.swing.JTextField employeeId_txt;
    private javax.swing.JButton insertregdata_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt;
    private javax.swing.JTextField roomNo_txt;
    private javax.swing.JButton search_btn;
    // End of variables declaration//GEN-END:variables
}
