/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projectui;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import db.DBconnect;
import java.sql.PreparedStatement;

/**
 *
 * @author charm
 */
public class Emp_Upd extends javax.swing.JFrame {

    /** Creates new form Emp_Reg */
    public Emp_Upd() {
        initComponents();
        setTitle("Manager");
        try{
       Connection conn = DBconnect.connect();
       String c = "SELECT * FROM `employee`";
       PreparedStatement st = null;
       st = conn.prepareStatement(c);
       ResultSet rs = st.executeQuery();
       DefaultTableModel tm = (DefaultTableModel)tbl_Update.getModel();
       tm.setRowCount(0);
    
       while(rs.next())
       {
            Object o[] = {rs.getInt("Employee_id"),rs.getString("NIC_no"),rs.getString("Name"),rs.getInt("Age"),rs.getString("Address"),rs.getString("Gender"),rs.getString("Emp_Category"),rs.getString("Registered_Date"),rs.getString("Mobile_no")};
            tm.addRow(o);
       }    

       }
       catch(SQLException e1) { JOptionPane.showMessageDialog(null, "Error", "Database Error", JOptionPane.ERROR_MESSAGE);}
       catch(Exception e) { JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE);}
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        txt_Search = new javax.swing.JTextField();
        emp_Id = new javax.swing.JTextField();
        emp_Name = new javax.swing.JTextField();
        mobile_No = new javax.swing.JTextField();
        emp_Age = new javax.swing.JTextField();
        emp_Address = new javax.swing.JTextField();
        rbn_Male = new javax.swing.JRadioButton();
        rbn_Female = new javax.swing.JRadioButton();
        emp_Type = new javax.swing.JComboBox<>();
        jButton10 = new javax.swing.JButton();
        btn_Update = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Update = new javax.swing.JTable();
        nic_No = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(85, 65, 118));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Employee Registration");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 143, 287, -1));

        jPanel5.setBackground(new java.awt.Color(85, 65, 118));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Employee Update");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 220, 287, -1));

        jPanel6.setBackground(new java.awt.Color(85, 65, 118));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Employee Delete");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 297, 287, -1));

        jPanel7.setBackground(new java.awt.Color(85, 65, 118));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Employee Login Management");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 374, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sign out");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 690, 120, 60));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 0, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Update Employee Records");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2715, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Employee ID");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 161, 22));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Full Name");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 202, 22));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Mobile Number");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 202, 22));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Age");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 202, 28));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Address");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 202, 22));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Gender");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 612, 202, 22));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Employee Category");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 664, 202, 22));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1104, 11, 513, 10));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1104, 596, 1, 10));

        txt_Search.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(txt_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 145, 255, 42));

        emp_Id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(emp_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 228, 42));

        emp_Name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(emp_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 228, 42));

        mobile_No.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(mobile_No, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 228, 42));

        emp_Age.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(emp_Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 228, 42));

        emp_Address.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(emp_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, 228, 42));

        rbn_Male.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbn_Male.setText("Male");
        jPanel3.add(rbn_Male, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 611, -1, -1));

        rbn_Female.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbn_Female.setText("Female");
        jPanel3.add(rbn_Female, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 611, -1, -1));

        emp_Type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Category", "Maintenance", "Front Desk Clerk", "Accountant", "Manager", "Housekeeping", "Kitchen staff" }));
        emp_Type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_TypeActionPerformed(evt);
            }
        });
        jPanel3.add(emp_Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 660, 228, 34));

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton10.setText("Search EID");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 144, 163, 42));

        btn_Update.setBackground(new java.awt.Color(255, 255, 255));
        btn_Update.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Update.setText("Update");
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });
        jPanel3.add(btn_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 715, -1, 42));

        jButton12.setBackground(new java.awt.Color(255, 255, 255));
        jButton12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton12.setText("Cancel");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 715, 82, 42));

        tbl_Update.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EID", "NIC No", "Full Name", "Age", "Address", "Gender", "Category", "Registered Date", "Mobile No"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_Update.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_Update.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tbl_Update.setShowHorizontalLines(false);
        tbl_Update.setShowVerticalLines(false);
        tbl_Update.getTableHeader().setReorderingAllowed(false);
        tbl_Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_UpdateMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Update);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 144, 1100, 462));

        nic_No.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(nic_No, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 228, 42));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("NIC No");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 161, 22));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emp_TypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_TypeActionPerformed

        
    }//GEN-LAST:event_emp_TypeActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        try{
       Connection conn = DBconnect.connect();
       String c = "SELECT * FROM `employee` where employee_id='"+txt_Search.getText()+"'";
       Statement st = null;
       st = conn.createStatement();
       ResultSet rs = st.executeQuery(c);
       
       String gender=null;
       String category = null;
       
       while(rs.next())
       {
            emp_Id.setText(String.valueOf(rs.getInt("employee_id")));
            nic_No.setText(rs.getString("NIC_No"));
            emp_Name.setText(rs.getString("Name"));
            emp_Age.setText(String.valueOf(rs.getInt("Age")));
            mobile_No.setText(rs.getString("mobile_No"));
            emp_Address.setText(rs.getString("Address"));
            gender = rs.getString("Gender");
            category = rs.getString("Emp_Category");
       }    
        if(gender.equalsIgnoreCase("male"))
        {
            rbn_Male.setSelected(true);
        }
        else
        {
            rbn_Female.setSelected(true);
        }
        emp_Type.setSelectedItem(category);
               
       }
       catch(SQLException e1) { JOptionPane.showMessageDialog(null, "Error", "Database Error", JOptionPane.ERROR_MESSAGE);}
       catch(Exception e) { JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE);}
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(null, "Do you want to update?", "Confirm",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION)
        {
        if(nic_No.getText().equals("")){JOptionPane.showMessageDialog(null, "Error", "NIC should not be empty", JOptionPane.ERROR_MESSAGE);}
        else if(emp_Name.getText().equals("")) {JOptionPane.showMessageDialog(null, "Error", "Name should not be empty", JOptionPane.ERROR_MESSAGE);}
        else if(emp_Age.getText().equals("")) {JOptionPane.showMessageDialog(null, "Error", "Age should not be empty", JOptionPane.ERROR_MESSAGE);}
        else if(mobile_No.getText().equals("")) {JOptionPane.showMessageDialog(null, "Error", "Mobile no should not be empty", JOptionPane.ERROR_MESSAGE);}
        else if(emp_Address.getText().equals("")) {JOptionPane.showMessageDialog(null, "Error", "Address should not be empty", JOptionPane.ERROR_MESSAGE);}
        else if(rbn_Male.isSelected()==false && rbn_Female.isSelected()==false){JOptionPane.showMessageDialog(null, "Error", "Select employee gender", JOptionPane.ERROR_MESSAGE);}
        else if(emp_Type.getSelectedIndex()==0){JOptionPane.showMessageDialog(null, "Error", "Select employee category", JOptionPane.ERROR_MESSAGE);}
        else{
        String gender = null;
        
            if(rbn_Male.isSelected())
            {
            gender = rbn_Male.getText();
            }
            else if(rbn_Female.isSelected())
            {
            gender = rbn_Female.getText();
            }
        
        try{
            Connection conn = DBconnect.connect();
            String c = "UPDATE employee set NIC_No='"+nic_No.getText()+"',Name='"+emp_Name.getText()+"',Age='"+emp_Age.getText()+"',Mobile_No='"+mobile_No.getText()+"',Address='"+emp_Address.getText()+"',Gender='"+gender+"',Emp_Category='"+emp_Type.getSelectedItem()+"' where Employee_id='"+emp_Id.getText()+"'";  
            Statement st = null;
            st = conn.createStatement();
            int i = st.executeUpdate(c);
            conn.close();
            if(i==1){
                JOptionPane.showMessageDialog(null, "Information", "Record updated successfully ", JOptionPane.INFORMATION_MESSAGE);
                Emp_Upd eu = new Emp_Upd();
                eu.setVisible(true);
                this.setVisible(false);
            }
            else{JOptionPane.showMessageDialog(null, "Error", "Error in updating record", JOptionPane.ERROR_MESSAGE);}
            }
            catch(SQLException e1) { JOptionPane.showMessageDialog(null, "Error", "Database Error", JOptionPane.ERROR_MESSAGE);}
            catch(Exception e) { JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE);}}
        
        }
    }//GEN-LAST:event_btn_UpdateActionPerformed

    private void tbl_UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_UpdateMouseClicked

     try{
        String gender = null;
       String category = null;
       DefaultTableModel model = (DefaultTableModel)tbl_Update.getModel();
       int selectedRowIndex = tbl_Update.getSelectedRow();
       
       emp_Id.setText(model.getValueAt(selectedRowIndex, 0).toString());
       txt_Search.setText(model.getValueAt(selectedRowIndex, 0).toString());
       nic_No.setText(model.getValueAt(selectedRowIndex, 1).toString());
       emp_Name.setText(model.getValueAt(selectedRowIndex, 2).toString());
       emp_Age.setText(model.getValueAt(selectedRowIndex, 3).toString());
       emp_Address.setText(model.getValueAt(selectedRowIndex, 4).toString());
       gender = model.getValueAt(selectedRowIndex, 5).toString();
       category = model.getValueAt(selectedRowIndex, 6).toString();
       mobile_No.setText(model.getValueAt(selectedRowIndex, 8).toString());
       
       if(gender.equalsIgnoreCase("male"))
        {
            rbn_Male.setSelected(true);
        }
        else
        {
            rbn_Female.setSelected(true);
        }
        emp_Type.setSelectedItem(category);}
       catch(Exception e) {JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE);}
    }//GEN-LAST:event_tbl_UpdateMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        Emp_Reg er = new Emp_Reg();
        er.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        Emp_Del ed = new Emp_Del();
        ed.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        Emp_Login_Manage el = new Emp_Login_Manage();
        el.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(null, "Do you want to log out?", "Confirm",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION)
        {
            Login l = new Login();
            l.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        Emp_Upd eu = new Emp_Upd();
                eu.setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Emp_Upd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Emp_Upd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Emp_Upd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Emp_Upd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Emp_Upd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Update;
    private javax.swing.JTextField emp_Address;
    private javax.swing.JTextField emp_Age;
    private javax.swing.JTextField emp_Id;
    private javax.swing.JTextField emp_Name;
    private javax.swing.JComboBox<String> emp_Type;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField mobile_No;
    private javax.swing.JTextField nic_No;
    private javax.swing.JRadioButton rbn_Female;
    private javax.swing.JRadioButton rbn_Male;
    private javax.swing.JTable tbl_Update;
    private javax.swing.JTextField txt_Search;
    // End of variables declaration//GEN-END:variables

}
